swagger: "2.0"
info:
  title: "Lesson 1: Authentication Microservice"
  description: A authentication microservice for generating tokens.
  termsOfService: https://www.udacity.com/legal
  contact:
    name: Jarrod Parkes
    url: http://jarrodparkes.com
    email: jarrod@udacity.com
  license:
    name: MIT
    url: https://github.com/udacity/ios-short-s3-auth/blob/master/LICENSE
  version: 1.0.0
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  token:
    type: basic
paths:
  /login:
    get:
      description: Returns a token to be used for accessing the monolith's secure endpoints.
      responses:
        200:
          description: Token
          schema:
            $ref: '#/definitions/Token'
definitions:
  Token:
    required:
      - token
    properties:
      token:
        type: string
    example:
      token: asdfadsflkjewrlkjsdal;jxc21335