FROM ibmcom/swift-ubuntu-runtime:5.0.1

MAINTAINER Jarrod Parkes <jarrod@udacity.com>

USER root

EXPOSE 8080

# Install system packages
RUN apt-get update; \
    apt-get dist-upgrade -y; \
    apt-get install -y librtmp0 login passwd; \
    apt-get install -y apt-utils uuid-dev libssl-dev software-properties-common; \
    add-apt-repository -y ppa:0k53d-karl-f830m/openssl; \
    apt-get update; \
    apt-get install -y openssl

ADD .build/x86_64-unknown-linux/debug/hello /root/app/
CMD [ "sh", "-c", "/root/app/hello"]