swagger: "2.0"
info:
  title: "Lesson 1: Hello Microservice"
  description: A microservice for simple messages.
  termsOfService: https://www.udacity.com/legal
  contact:
    name: Jarrod Parkes
    url: http://jarrodparkes.com
    email: jarrod@udacity.com
  license:
    name: MIT
    url: https://github.com/udacity/ios-short-s3-hello/blob/master/LICENSE
  version: 1.0.0
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  token:
    type: basic
paths:
  /:
    get:
      description: Returns \"hello, world\" message.
      responses:
        200:
          description: A \"hello, world\" message.
          schema:
            $ref: '#/definitions/Message'
  /secure:
    get:
      security:
        - token: []
      description: Returns a secure message.
      responses:
        200:
          description: A \"hello, world\" message.
          schema:
            $ref: '#/definitions/Message'
        401:
          description: Not authenticated.
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string
    example: 
      message: Hello world!